/**
 * gsapのビルトインプロパティ
 */
export const GSAP_BUILTIN_PROPERTY_KEYS = [
  'autoCSS',
  'callbackScope',
  'delay',
  'duration',
  'ease',
  'immediateRender',
  'lazy',
  'onComplete',
  'onCompleteParams',
  'onCompleteScope',
  'onStart',
  'onStartParams',
  'onStartScope',
  'onOverwrite',
  'onRepeat',
  'onRepeatParams',
  'onRepeatScope',
  'onReverseComplete',
  'onReverseCompleteParams',
  'onReverseCompleteScope',
  'onUpdate',
  'onUpdateParams',
  'onUpdateScope',
  'overwrite',
  'paused',
  'repeat',
  'repeatDelay',
  'startAt',
  'useFrames',
  'yoyo',
  'yoyoEase',
] as const
